### ISSUE TITLE
Can't get all Blooks

### ISSUE THREAD

**Issue by Maxolotl07** [glixzzy/blooket-hack#306]
Whenever I try to do the "get all books" hack t never seems to work. Is this just a temporary hack so that's why it doesn't show up in my books menu. Or is it just a thing that works for one game?

**Comment by wesley61** [comment]
Frequently Asked Questions
Note: Before you make an issue or ask someone on the support server, please go through the FAQ to check if it is in here. Thank you.

Q: The all permanent blooks isn't working!

A: Yes, it was a joke and does not permanently work.

Q: Is there any way to bypass the 500 token per day limit or change the time before reset timer?

A: Nope! This is simply not possible, because it is server-side.

Q: Can I make custom blook skins and use them in game?

A: Yes and no. This is possible even without these hacks, if you gain enough xp through grinding or using the addTokens hack, you will be able to make your own custom blooks under the Stats tab on Blooket. But if you are trying to upload your own fully custom blooks, this is not currently possible, as all blooks are server-side.

Q: Ahhh! My account was banned! Was I just banned for hacking blooket? Screen Shot 2021-10-07 at 6 39 06 PM

A: Probably not, this is a bug that is going around that doesn't let you in your account for a short period of time. The best thing to do is just wait it out.

**Comment by glixzzy** [comment]
only works in /play/lobby

**Comment by Himynameiskevin** [comment]
can you use a new acount and make new hacks?
you can try to give us infinite blooks so we can go over the max token limit

**Comment by FullBlookHackPlsInBlookSection** [comment]
come back and secretly do the hack and maybe could do some more coding to figure out if you can do more than 500 and make it ever like hour please me and my friends at school really loved your hacks so please come back but now me and 2 of my friends are using a different website for 500 coins but i wish it was 1000 coins or something thank for the hack brotha but yeah thank tho. 

Sincerely,
iHackBloket4Fun/iHackBlooket4Fun, if I had more character space. Bye
