### ISSUE TITLE
Chest ESP in Gold Rush is not working properly.

### ISSUE THREAD

**Issue by BbyfoxY** [glixzzy/blooket-hack#516]

**Comment by marfanis788** [comment]
Does it mess up the second question?

**Comment by 3kh0** [comment]
@BabyfxY what do you mean it is not working?

**Comment by BbyfoxY** [comment]
It does not work sometimes when you use it on the chest page

**Comment by CollynGaming** [comment]
the chest esp works but it does not show the correct item in the chest the esp may sho SWAP but the chest has lose 50%

**Comment by 3kh0** [comment]
**TO CLARIFY HOW THE CHEST ESP WORKS**

You must run the bookmarklet or code every time you get to the chest selection page. Otherwise, it WILL NOT WORK! 

Also sometimes blooket does some weird bullcrap and the bookmarklet can not detect the prize page. A workaround is being worked on.

@BbyfoxY @CollynGaming

**Comment by glixzzy** [comment]
fixed
