### ISSUE TITLE
this is a question, but can u give me write access beacsue i gave 2 commits

### ISSUE THREAD

**Issue by coolawsome2009** [glixzzy/blooket-hack#522]

**Comment by Greenlio** [comment]
bro there's people with tens of commits and don't have collaborator. just because you did some blizzard box swag doesn't mean you can get the funny write access lmao

I don't even ask for write access, as I don't have any need for it atm lol.
however, closing issues would be cool but isn't that big of a deal

**Comment by glixzzy** [comment]
make a pull request.

**Comment by 3kh0** [comment]
@coolawsome2009 never beg for permissions, you won't get them. People have done over 20 pr's but they don't have direct write access.

**Comment by Greenlio** [comment]
^^

**Comment by Greenlio** [comment]
only 3 people have write access

**Comment by 3kh0** [comment]
> ^^

Thanks! ❤️
