### ISSUE TITLE
box spam is not working

### ISSUE THREAD

**Issue by rainy1228** [glixzzy/blooket-hack#527]
box spam is not working

**Comment by 3kh0** [comment]
**Hello there!**

Your issue is not complete and we can not tell the problem!<br>

Here are some questions you should answer when creating an issue:
- What browser do you use? 
- Are you on a school computer and/or connected to the school internet?
- Are you using a bookmarklet or are you pasting the code into the console?
- Has the code worked before?
- Is it the original code? This is what the original code would look like: `fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vc2Nob29sLWNoZWF0cy9yYXcvdXBsb2FkL3YxNjM3NDUyMjEzL2dsb2JhbFNwYW1PcGVuQm94ZXMuanM=')).then((res) => res.text().then((t) => eval(t)))`

Thank you for letting us know the issue! 😀

**Comment by rainy1228** [comment]
-i use google chrome
-this is my own computer connected to my own wifi
-pasting the code into the console
-yes
-yes, it is the original code

**Comment by 3kh0** [comment]
> -i use google chrome -this is my own computer connected to my own wifi -pasting the code into the console -yes -yes, it is the original code

try using the bookmarklet method

**Comment by rainy1228** [comment]
still doesn't work :(

**Comment by 3kh0** [comment]
> still doesn't work :(

How are you using the bookmarklet? Make sure you add `javascript:` to the beginning of the code.

**Comment by rainy1228** [comment]
i did

**Comment by glixzzy** [comment]
fixed
