### ISSUE TITLE
hack is not get answer

### ISSUE THREAD

**Issue by Imagoodboy1** [glixzzy/blooket-hack#570]

**Comment by 3kh0** [comment]
**Hello there!**

Your issue is not complete and we can not tell the problem!<br>

Here are some questions you should answer when creating an issue:
- What browser do you use? 
- Are you on a school computer and/or connected to the school internet?
- Are you using a bookmarklet or are you pasting the code into the console?
- Has the code worked before?
- Is it the original code? This is what the original code would look like: `fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vc2Nob29sLWNoZWF0cy9yYXcvdXBsb2FkL3YxNjM3NDUyMjEzL2dsb2JhbFNwYW1PcGVuQm94ZXMuanM=')).then((res) => res.text().then((t) => eval(t)))`

Thank you for letting us know the issue! 😀

**Comment by glixzzy** [comment]
literally makes no sense.

**Comment by 3kh0** [comment]
> literally makes no sense.

I know right? so annoying!

**Comment by TheGamer1002** [comment]
@glixzzy Could you please close this one? Thanks!

**Comment by 3kh0** [comment]
> @glixzzy Could you please close this one? Thanks!

We are waiting to see if @Imagoodboy1 will provide more classifcation

**Comment by TheGamer1002** [comment]
Ah, okay

**Comment by donaldli2020** [comment]
> > literally makes no sense.
> 
> I know right? so annoying!

i guess he means all answers correct is not working?

**Comment by Greenlio** [comment]
It could be one of like three things.
A) the gamemode isn't supported for all answers correct.
B) they're doing it wrong.
C) they're using an old link. I'll say it again.

https://schoolcheats.net for an updated copy.
