### ISSUE TITLE
changeGameRound.js is error occured

### ISSUE THREAD

**Issue by HahHeanKee** [glixzzy/blooket-hack#622]
I use the command, and he said error 404, not working
![image](https://user-images.githubusercontent.com/79510577/145172130-bffe54fb-2302-4cc6-ba6d-c3c90256ed15.png)

**Comment by HahHeanKee** [comment]
I cannot testing elf legendary vs king legendary!!!

**Comment by Nobody-720** [comment]
**Tower Defense**

**Comment by 3kh0** [comment]
**Hello there!**

Your issue is not complete and we can not tell the problem!<br>

Here are some questions you should answer when creating an issue:
- What browser do you use? 
- Are you on a school computer and/or connected to the school internet?
- Are you using a bookmarklet or are you pasting the code into the console?
- Has the code worked before?
- Is it the original code? This is what the original code would look like: `fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vc2Nob29sLWNoZWF0cy9yYXcvdXBsb2FkL3YxNjM3NDUyMjEzL2dsb2JhbFNwYW1PcGVuQm94ZXMuanM=')).then((res) => res.text().then((t) => eval(t)))`

Thank you for letting us know the issue! 😀

**Comment by HahHeanKee** [comment]
done, just solve it

**Comment by HahHeanKee** [comment]
It agains 
<img width="959" alt="image" src="https://user-images.githubusercontent.com/79510577/145314597-db25cf7c-5b64-4bdb-8aa6-1a1fce3b9d87.png">

**Comment by 3kh0** [comment]
**Hello there!**

Your issue is not complete and we can not tell the problem!<br>

Here are some questions you should answer when creating an issue:
- What browser do you use? 
- Are you on a school computer and/or connected to the school internet?
- Are you using a bookmarklet or are you pasting the code into the console?
- Has the code worked before?
- Is it the original code? This is what the original code would look like: `fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vc2Nob29sLWNoZWF0cy9yYXcvdXBsb2FkL3YxNjM3NDUyMjEzL2dsb2JhbFNwYW1PcGVuQm94ZXMuanM=')).then((res) => res.text().then((t) => eval(t)))`

Thank you for letting us know the issue! 😀

**Comment by HahHeanKee** [comment]
walao, I already have a clue

**Comment by HahHeanKee** [comment]
Glizzy???

**Comment by HahHeanKee** [comment]
> **Hello there!**
> 
> Your issue is not complete and we can not tell the problem!
> 
> Here are some questions you should answer when creating an issue:
> 
> * What browser do you use?
> * Are you on a school computer and/or connected to the school internet?
> * Are you using a bookmarklet or are you pasting the code into the console?
> * Has the code worked before?
> * Is it the original code? This is what the original code would look like: `fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vc2Nob29sLWNoZWF0cy9yYXcvdXBsb2FkL3YxNjM3NDUyMjEzL2dsb2JhbFNwYW1PcGVuQm94ZXMuanM=')).then((res) => res.text().then((t) => eval(t)))`
> 
> Thank you for letting us know the issue! 😀
walao, I already have a clue

**Comment by 3kh0** [comment]
something is wrong with the URL in the screenshot. Try refreshing the page if the hack does not work. That fix works for me.

**Comment by HahHeanKee** [comment]
also not working

**Comment by HahHeanKee** [comment]
I already reload
