### ISSUE TITLE
github/hacks for blooket

### ISSUE THREAD

**Issue by mohammad126** [glixzzy/blooket-hack#693]
hi glixzzy will the hacks for blooket go to github soon because schoolcheats.net is blocked for  me

**Comment by LILHOLLOW** [comment]
yea itsblocked for me to

**Comment by varedz** [comment]
They’re already on GitHub in the folders.

**Comment by littlekevinandtheboys** [comment]
bro literally go to global or whatever you want and click the hacks themselves and you can copy it, like instead of scrolling or clicking the readme click into the hacks themselvesbro literally go to global or whatever you want and click the hacks themselves and you cbro literally go to global or whatever you want and click the hacks themselves and you can copy it, like instead of scrolling or clicking the readme click into the hacks themselvesbro literally go to global or whatever you want and click the hacks themselves and you can copy it, like instead of scrolling or clicking the readme click into the hacks themselvesbro literally go to global or whatever you want and click the hacks themselves and you can copy it, like instead of scrolling or clicking the readme click into the hacks themselvesbro literally go to global or whatever you want and click the hacks themselves and you can copy it, like instead of scrolling or clicking the readme click into the hacks themselvesbro literally go to global or whatever you want and click the hacks themselves and you can copy it, like instead of scrolling or clicking the readme click into the hacks themselvesbro literally go to global or whatever you want and click the hacks themselves and you can copy it, like instead of scrolling or clicking the readme click into the hacks themselvesan copy it, like instead of scrolling or clicking the readme click into the hacks themselves
