### ISSUE TITLE
Gold Quest Chest ESP + Spam Open Boxes Doesn't work on a school chrome book (Inspect or bookmarklet)

### ISSUE THREAD

**Issue by Goldenium11** [glixzzy/blooket-hack#990]
Whenever I try to use chest esp on a gold quest, it works on my desktop, but it does not work on my Chromebook. It tells me to join a gold quest game when I'm not on a gold quest game, but when I go to a gold quest game, it doesn't say anything at all and does not work. It used to work but it no longer does even when I get the latest script (BTW: I use bookmarklets for all the hacks). Also when I try to use the Spam Open boxes, it first, doesn't work at all on my Chromebook, bookmarklet, or not, but it only works on my desktop if I use to inspect and paste it into the console (Does Not Work as a bookmarklet). Is there any way to make either work?

**Comment by jrs1rules** [comment]
use the updated verison of it,

**Comment by blookieboo** [comment]
yes. I type javascript:(the code)
then it doesnt do anything

**Comment by GooseterV** [comment]
Make sure you're using the latest version off of github and not schoolcheats or other providers. The bookmarklets should all work fine, seeing as it's just running the code a different way.

**Comment by OrpTheHacker** [comment]
You are supposed to use just one hack for each game because multiple hacks in 1 game doesn't work anymore for some reason. And if you still get the problem then change your code to the latest newest in Blooket and when you make a bookmark type javascript:(the code in here) and that should work since it is working for me in a Chromebook. If you don't know how to do the javascript then just copy the code from my pastebins from here and paste the code in a bookmark and save it : https://controlc.com/mypastes.php
